#Spring cloud gateway configuration :------------------------------------------------------------------------------
spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-MICROSERVICE
          uri: lb://AUTH-MICROSERVICE
          predicates:
          - Path=/api/**

        - id: FRONTEND-MICROSERVICE
          uri: lb://FRONTEND-MICROSERVICE
          predicates:
            - Path=/auth/**

#okta configuration :---------------------------------------------------------------------------------------------------
okta:
  oauth2:
    issuer: https://dev-48871311.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa96yxs1jRYZol7B5d7
    client-secret: Kjlkd30Hz8qKNzBEUu_ItXTp2UIpyF37Kk_XswG1
    scopes: openid, profile, email, offline_access