#Springboot Actuator configuration :------------------------------------------------------------------------------------
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#resilience4j configuration :-------------------------------------------------------------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      apiAuthBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      apiAuthService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      apiAuthRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

